import { DataTypes } from "sequelize";
import { sequelize } from "../db/sequelize.js";
import crypto from "crypto";

const ChatRoom = sequelize.define('ChatRoom', {
    id: {
        type: DataTypes.UUID,
        defaultValue: DataTypes.UUIDV4,
        primaryKey: true,
    },
    name: {
        type: DataTypes.STRING,
        allowNull: false,
    },
    // the code is autogenerated when the room is created, and is used to join the room
    inviteCode: {
        type: DataTypes.STRING,
        allowNull: false,
        unique: true,
    },
    // to be updated when a message is sent so chatrooms can be ordered by most recent msg
    lastMsgSent: {
        type: DataTypes.DATE,
        allowNull: true,
    },
    // a room without recent question answers is marked as inactive
    isActive: {
        type: DataTypes.BOOLEAN,
        defaultValue: true, // new rooms start as active
        allowNull: false,
    },
}, {
    tableName: 'chatroom',
    timestamps: true,
    hooks: {
        // when the chatroom is created, generate an invite code
        beforeValidate: (chatroom, options) => {
            chatroom.inviteCode = crypto.randomBytes(3).toString('hex').toUpperCase();
        },
    }
});

export default ChatRoom;