/*
2. signup function takes in username, email, password from the request body
-> ensure none of the fields are empty

5. database confirms save -> user is created with a unique ID (uid) generated by the database
-> return success response to frontend with the new user's unique ID, return new user object + uid back to controller
-> send 201 response to frontend with the new user's unique ID
 */

import User from '../models/userModel.js'; // Import the Sequelize User model
import { Op } from 'sequelize'; // Import Operators for complex queries

export const signup = async (req, res) => {
    try {
        const { username, email, password } = req.body; // Destructure the request

        // Validate that no fields are missing
        if (!username || !email || !password) {
            return res.status(400).json({ error: "Missing required fields" });
        }

        // 1. Duplicate Check: User.findOne(...)
        const existingUser = await User.findOne({
            where: {
                [Op.or]: [{ username }, { email }] // Check if either username OR email exists
            }
        });

        if (existingUser) {
            return res.status(400).json({ error: "Username or email already recorded" });
        }

        // 2. Create User: User.create(...)
        // The password_hash hook in the model will handle encryption automatically
        const newUser = await User.create({
            username,
            email,
            password_hash: password 
        });

        // 3. Return Success with Unique ID
        return res.status(201).json({
            message: "User created successfully",
            userId: newUser.uid 
        });

    } catch (error) {
        console.error("Signup Error:", error);
        res.status(500).json({ error: "Internal server error" });
    }
};

// // Logic to handle user sign up
// async function signup(req, res) {
//     try {
//         const { username, email, password } = req.body; // Extract username/password

//         // 1. Validate required fields
//         if (!username || !email || !password) {
//             return res.status(400).json({ error: "Missing required fields" });
//         }

//         // 2. Check if username already exists (Duplicate Check)
//         const existingUser = await userModel.getUserByUsernameOrEmail(username, email);
//         if (existingUser) {
//             return res.status(400).json({ error: "Username or email already recorded" });
//         }

//         // 3. Create the user (Password is hashed in the model)
//         const newUser = await userModel.createUser({ username, email, password });

//         // 4. Return success with the Unique ID
//         return res.status(201).json({
//             message: "User created successfully",
//             userId: newUser.uid,
//             email: newUser.email
//         });

//     } catch (error) {
//         console.error(error);
//         res.status(500).json({ error: "Internal server error" });
//     }
// }

// module.exports = { signup }; // Export the controller function